@startuml
'https://plantuml.com/activity-diagram-beta

start
:Получаем информацию о кадастровой зоне;
:Берем точку, которая точно принадлежит зоне;
:Запрашиваем территориальную зону по точке;
:Запрашиваем функциональную зону по точке;
:Формуруем ответ для отправки боту;
stop

@enduml
